### ISSUE TITLE
New Video Project not calculating traces

### ISSUE THREAD

**Issue by snguyen49** [RNA-FRETools/MASH-FRET#114]
Hi, 

I tried to import a video created from the simulation to try out the video project function. After inputting all of the spot coordinates and mapping the reference coordinates, I tried to calculate the traces. The system then showed an error and was not able to calculate the traces.

![Screenshot 2024-01-10 142012](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/1e31ea37-4b24-4511-bb02-bbb4590e474b)
This is the error code.

![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/d88dd0bc-fc49-4009-bbf8-20ceceac8acc)
These were the parameters.

Many Thanks,
Sydney Nguyen

**Comment by mca-sh** [comment]
Hello Sydney and thank you for reporting this bug.
Could you please save the project to a .mash file and send it to me? 
I will try to reproduce the error and have a look at what went wrong.

Best,
Mélodie

**Comment by snguyen49** [comment]
Hi Mélodie,

I have attached the .mash file in this email.

Many Thanks,
Sydney Nguyen
________________________________

**Comment by mca-sh** [comment]
Oups
Sorry, but attaching files to emails does not work here since we are mediated via Github.
Could you please come to Github and send it from the issue you've posted (https://github.com/RNA-FRETools/MASH-FRET/issues/114)?
Thank you.

**Comment by snguyen49** [comment]
[calculatingtraceserror.zip](https://github.com/RNA-FRETools/MASH-FRET/files/13907145/calculatingtraceserror.zip)

**Comment by snguyen49** [comment]
My bad. I am not good with this computer stuff.
________________________________

**Comment by mca-sh** [comment]
No worries that's a common mistake.
Actually I would need also the associated video file (.sira I think).
This might be too large for Github though..

**Comment by mca-sh** [comment]
Otherwise I will have to ask you many questions since I cant reproduce the error by doing the same steps as you did.

**Comment by snguyen49** [comment]
I see. Is there any other way I can use to send it to you?
________________________________

**Comment by mca-sh** [comment]
Can you try to send it to my email address: melodiehadzic@protonmail.com
Or, if it is still too big, you can try via this swiss website: https://www.grosfichiers.com/en/

**Comment by snguyen49** [comment]
I just sent the file via the swiss website.

Thank you,
Sydney
________________________________

**Comment by mca-sh** [comment]
Great thank you, I will have a look

**Comment by mca-sh** [comment]
Hi Sidney,
I had a look and can't find what went wrong.
The video file you sent me might not the exact one with which you've created the video-based project since the average image changed drastically when I recalculated.
Anyway, it does not matter much.
You can try to reset the defaults interface parameters by:
1. closing MASH
2. deleting the file MASH-FRET/default_param.ini
3. reopen MASH and re-create your video project

One suspicion I have is that, may be, the number of lasers was not well defined in the experiment settings.
It should one laser in your case.

Please tell me if you still have this bug arising despite the procedure.

Best,
Mélodie

**Comment by mca-sh** [comment]
I found a bug that might be related.
Can you try with this version please: https://codeload.github.com/RNA-FRETools/MASH-FRET/zip/refs/heads/correct-doublon-coord

**Comment by snguyen49** [comment]
Thank you. I will try it out and get back to you.

Sydney Nguyen
________________________________

**Comment by snguyen49** [comment]
Hi Melodie,

So far, it seems to be working fine. I will let you know if there is anything else that pops up pertaining to this issue.

Thank you so much for your help!
Sydney Nguyen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mca-sh** [comment]
Hi Sidney and thank you for your feedback,

I don't mind your questions, they also help me develop the software.
I understand you are in a hurry to analyze your data and I 'll try my best.

I do not see the images you included in your message, probably because they are attached to your email. 
Could you please use Github directly (https://github.com/RNA-FRETools/MASH-FRET/issues/114)?
Thank you
Mélodie

**Comment by mca-sh** [comment]
I try to reproduce the problem that you might have by:
1. simulating and exporting a .sira video file, 
2. creating a video project using this video file, and 
3. creating trajectories.

The difference you are observing between your simulated and video-extracted trajectories might come from the **background** and **cross-talk** corrections that are not configured for your data.
These are an important part of trace processing and must be done every time you process new data.

### Background correction
For the background correction, check that the correction is applied for each of the trajectory (module `Trace processing` > panel `Background correction`). 
I recommend to use the method `<N median values>` with option `dynamic` activated. It is more time consuming but more precise. 
Be sure the correction is applied (option `Apply` activated) for each trajectory in the list `data`, and use the same setting for each molecule by pressing `All`.
If you want more information about background correction, please visit this section of the online doc: https://rna-fretools.github.io/MASH-FRET/trace-processing/components/panel-background-correction.html

### Cross-talk correction
First, be sure of the cross-talk (bleedthrough and direct excitation) coefficients you used: they are specific to your experimental setup. In your case, they were defined in the simulation.
Look for the donor bleedthrough coefficient set in the simulation (module `Simulation` > panel `Molecules` > field `BtD`) and report the exact same value to your trajectory processing (module `Trace processing` > panel `Cross-talks` > set `emitter` to donor > set `bt into` to acceptor > field `bt`).
The cross-talk coefficients are common to all molecules.

I hope this fixes the problem, otherwise, I will need your images.

Mélodie

**Comment by snguyen49** [comment]
Thank you, Melodie! I will try it out as soon as possible and get back to you with the results.
________________________________

**Comment by snguyen49** [comment]
Hey Melodie, 
I am currently using the most recently updated file you sent me but it is now reproducing the same error from the original issue that I had presented in this post. I am not sure what I am doing wrong, but here is a screenshot of the error code. 
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/5f560261-71c7-4bc5-b0a6-174b1bc648e5)

**Comment by mca-sh** [comment]
Hi Sydney,

I see, so the problem was elsewhere.. 

Can you please detail the steps you went through?
Are you working with the same project and video file you sent me?

**Comment by snguyen49** [comment]
Hi Melodie,

I basically simulated a new system with the default parameters with 1000 frames and 100 molecules. Once I had acquired the simulation, I exported the corresponding avi and sira videos and coordinates. After that, I started a new video project and imported the newly simulated video. I used the spotfinder with Houghpeaks and mapped the reference coordinates. I also the spot coordinates were transformed and calculated for the transformation so I had all three green check marks as advised on the website.

**Comment by mca-sh** [comment]
Ok, you did exactly what we are supposed to do.

I have a question about the experiment settings: when you created your video-based project, how many alternating lasers did you set in the tab "lasers" (like below)?

![image](https://github.com/RNA-FRETools/MASH-FRET/assets/7199132/1d5c288d-caae-4282-bc09-a6dd5970e8b2)

**Comment by snguyen49** [comment]
I set it as one. Should I have set it as 2?

**Comment by mca-sh** [comment]
No, you're right everything is correct.
I don't understand where the problem is coming from, because when I repeat the procedure, everything works fine.

I have two questions:
1. Did you use the avi or the sira file in the video-based project?
2. May I ask you to press "Transform" and send me a screen shot of Video Processing after coordinates are transformed? May be no coordinates is left after transformation.

**Comment by snguyen49** [comment]
I am currently using the .sira file instead of .avi. 
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/6d0b43cf-3895-4669-a4ca-13b56ac6a191)

**Comment by snguyen49** [comment]
Yes. I tried transforming and calculating again, but it is generating the same error.

**Comment by mca-sh** [comment]
Ok, can you expand the "Intensity integration" panel so I can have a look at the parameters?

What may have work the last time is to delete the default_param.ini file. May be you can repeat this and see if it fixes the problem?

**Comment by snguyen49** [comment]
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/f8fbdbcf-b529-47e1-9561-9a1bebc5a15b)

**Comment by mca-sh** [comment]
> You can try to reset the defaults interface parameters by:
> 
>     1. closing MASH
> 
>     2. deleting the file MASH-FRET/default_param.ini
> 
>     3. reopen MASH and re-create your video project

**Comment by mca-sh** [comment]
So you did not delete this file the last time?
The intensity integration  parameters are fine.. I can't see where the bug is coming from..

**Comment by snguyen49** [comment]
> So you did not delete this file the last time? The intensity integration parameters are fine.. I can't see where the bug is coming from..

I am currently trying it out right now. Will see how it goes.

**Comment by mca-sh** [comment]
I will analyze your logs then, that's my last chance to udnerstand what is going on.
Could you please give the file `MASH-FRET/log/[XXXX-XX-XX].log` with [XXXX-XX-XX] today's date?

**Comment by snguyen49** [comment]
After deleting the default parameters file, it is now working.

**Comment by mca-sh** [comment]
Mmm.. I will have a look at what parameter can make such mess.

And 5 days ago, did you delete this file? Because this might have been why the problem was solved.

**Comment by snguyen49** [comment]
I do not believe I had deleted the file 5 days ago.

**Comment by mca-sh** [comment]
Ok. Next time you get this error, could you send me the `default_param.ini` file so I can investigate where the conflict come from?
Thanks!

**Comment by snguyen49** [comment]
Unfortunately, I am still not acquiring the same trace results in my video project as found from the simulation. I had set the bleedthrough to 0.07 for the donor channel as given in the simulation. I am not sure as to what I may be doing wrong.
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/f5ff0ed6-db94-4457-85c7-98b9ac4b96e4)
These are the traces from the video project.
![image](https://github.com/RNA-FRETools/MASH-FRET/assets/142941188/5d5a7b42-7f4f-4121-87c0-93c3bbc86ef0)
These are the traces from the simulation.
Thank you for the help.
Sydney Nguyen

**Comment by mca-sh** [comment]
Thank you for the images.
I can see two things:
1. It seems from your screenshot of video processing, that too many dark spots were targetted (no molecule is present). and this is confirmed by your screenshot of trace processing where the integration zones (red and yellow squares) are empty. If you navigate through the molecule list, you will eventually fall on one real molecule. To prevent this "overfinding" of spots in the video, you need to adjust the parameters of the Houghpeaks function, especially the first one that is the low intensity threshold of a bright spot to be detected. To know what value to use, you need to check the color bar in the average image plot and select the value corresponding to the color of a single molecule in the average image.
2. The second thing is that the background is not corrected, at least for the red signal (acceptor signal). You need to browse the `data` pop up and set the background parameters for each data in the list as they are data-specific. Please have a look at my previous message of yesterday that explains everything about background settings (https://github.com/RNA-FRETools/MASH-FRET/issues/114#issuecomment-1891958018).

Let's see if we obtain the same traces then.

**Comment by mca-sh** [comment]
> Hey Melodie, I have attached the original default parameters file that I deleted previously. Many Thanks, Sydney Nguyen

I can't access it, you need to send it via Github sorry.

**Comment by snguyen49** [comment]
[default_param.zip](https://github.com/RNA-FRETools/MASH-FRET/files/13955102/default_param.zip)
Sorry about that. Here you go. And thank you, I will go over your tips and let you know if there are any other run-ins.

**Comment by mca-sh** [comment]
Great thank you!

**Comment by snguyen49** [comment]
I DID IT! Thanks Melodie. T^T

**Comment by mca-sh** [comment]
Hi Sydney,
Great that it worked out :)
Don't apology, your concerns are all fair.

Just in case you are still wondering: 1) to correct for acceptor direct excitation, you need a signal of the acceptor upon "red" laser excitation, and unfortunately, simulation is available only for one laser.. This is why the correction is not available in trace processing. 2) the intensity trajectories in the simulation tab are not background- and crosstalk-corrected, this is why you see such discrepancy.

I checked the content of the `default_prm.ini` file but nothing strange was in there.. I really can't figure out what happened.

I will close the issue now (which is very long ^^).
You can open a new one anytime.

Best,
Mélodie
