### ISSUE TITLE
Error loading .pma file

### ISSUE THREAD

**Issue by BenjaminAmbrose** [RNA-FRETools/MASH-FRET#81]
Hi all,

I get an error when trying to load in .pma files from our microscope. It says;

>LoadPMA: Cannot get a complete set of frames out of this file. Something is wrong.

I've attached a sample .pma file below if you want to take a look. 

[beads1.zip](https://github.com/RNA-FRETools/MASH-FRET/files/9243933/beads1.zip)

Many thanks,
Ben

**Comment by mca-sh** [comment]
Hello Ben,

Thank you for reporting this bug.
I am modifying the import function according to your file.
Can you confirm (or not) that your video is of pixel dimensions 512x512 and consists in 51 video frames?
Thanks!

Mélodie

**Comment by BenjaminAmbrose** [comment]
Hi Mélodie,

That's correct yes!

Ben

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mca-sh** [comment]
Hello Ben,

Alright, thank you for your answer.
The bug was corrected in this patched version: https://github.com/RNA-FRETools/MASH-FRET/archive/refs/heads/fix-pma-reading.zip.
The patch will be included in the next software release.

Please tell me if everything is working for you.

Mélodie

**Comment by pflanzenhueter** [comment]
Dear all,
I have reviewed and merged (into master branch) the pull request.
Best, Richard

**Comment by BenjaminAmbrose** [comment]
Hi All,

Thanks for looking at this for me. MASH-FRET will now start loading the file but gives a new error part way in;

```
Error using reshape
Number of elements must not change. Use [] as one of the size
inputs to automatically calculate the appropriate size for that
dimension.

Error in readPma (line 150)
                h.movie.movie(:,:,i) = flip(reshape(...

Error in getFrames (line 38)
            [data,ok] = readPma(fullFname, n, param, h_fig, useMov);

Error in loadMovFile (line 56)
[data,ok] = getFrames([pname fname], n, [], h_fig, true);

Error in pushbutton_loadMov_Callback (line 20)
if ~loadMovFile('all',argin,1,h_fig);
 
Error while evaluating UIControl Callback.
```

Cheers,
Ben

**Comment by mca-sh** [comment]
Hello Ben and thank you for your feedback.
There are two things I need to know to fix the problem:

1) Could you tell me what are the exact steps that you performed to get to this error?
I've tried to import your pma file by:
- pressing "Load" in Video processing
- selecting your pma file in the browser
And the file was correctly imported in MASH.

2) How are you getting MASH:
- Are you downloading the .zip archive (from the link I gave you in my previous message), or,
- Are you cloning the master branch from Github?
In the first case, you need to delete all the previous MASH versions from your computer before you run the new version as these can lead to conflicts.

Best,
Mélodie

**Comment by BenjaminAmbrose** [comment]
Hi Mélodie,

I've deleted the original directory and installed the one in your link but I am still getting the same problem,

Ben

**Comment by mca-sh** [comment]
Hi Ben and thanx again for your feedback,

I was finally able to test this feature and indeed, I got the same error.
The problem is fixed for me in the corrected version.
You can use the same link I gave you in my previous message to download it as it is automatically updated.

Please tell me if it is also working for you.
Mélodie

**Comment by BenjaminAmbrose** [comment]
Hi Mélodie

It's working now! Many thanks for your efforts fixing this

Ben

**Comment by mca-sh** [comment]
Great, thank you for helping us with solving bugs!
And do not hesitate to post another issue if you encounter more bugs or have questions.

I close this issue now

Mélodie
